### ISSUE TITLE
test_command_iterator_api_interrupted_sync: CRITICAL Runner._close process still running <Process 4556>

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/shellous#150]
```
tests/test_shellous.py::test_command_iterator_api_interrupted_sync 
------------------------------- live log setup --------------------------------
1635988954.812 DEBUG asyncio Using proactor: IocpProactor
1635988954.813 DEBUG asyncio Using proactor: IocpProactor
1635988954.814 DEBUG asyncio Close <ProactorEventLoop running=False closed=False debug=True>
-------------------------------- live log call --------------------------------
1635988954.817 DEBUG asyncio Using proactor: IocpProactor
1635988954.819 INFO shellous Runner.__aenter__ stepin <Runner 'echo' pid=None> (Windows-10 CPython 3.10.0 asyncio.windows_events.ProactorEventLoop MainThread)
1635988954.819 INFO shellous Runner._start stepin <Runner 'echo' pid=None>
1635988954.819 INFO shellous Runner._subprocess_spawn stepin <Runner 'echo' pid=None>
1635988954.821 INFO shellous Runner._subprocess_exec stepin <Runner 'echo' pid=None>
1635988954.822 DEBUG asyncio execute program 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shellous-j1zXeGWZ-py3.10\\Scripts\\python.exe' stdin=<pipe> stdout=<pipe> stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='cp1252'>
1635988954.825 DEBUG asyncio process 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shellous-j1zXeGWZ-py3.10\\Scripts\\python.exe' created: pid 4556
1635988954.828 DEBUG asyncio Write pipe 2204 connected: (<_ProactorWritePipeTransport fd=2204 read=<_OverlappedFuture pending overlapped=<pending, 0x24dce8aaa70> cb=[_ProactorWritePipeTransport._pipe_closed()] created at C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\windows_events.py:465>>, <WriteSubprocessPipeProto fd=0 pipe=<_ProactorWritePipeTransport fd=2204 read=<_OverlappedFuture pending overlapped=<pending, 0x24dce8aaa70> cb=[_ProactorWritePipeTransport._pipe_closed()] created at C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\windows_events.py:465>>>)
Traceback (most recent call last):
  File "D:\a\shellous\shellous\tests\python_script.py", line 36, in <module>
    _write(data)
  File "D:\a\shellous\shellous\tests\python_script.py", line 17, in _write
    sys.stdout.buffer.flush()
OSError: [Errno 22] Invalid argument
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
1635988954.830 DEBUG asyncio Read pipe 2020 connected: (<_ProactorReadPipeTransport fd=2020 read=<_OverlappedFuture pending overlapped=<pending, 0x24dce8a89d0> cb=[_ProactorReadPipeTransport._loop_reading()] created at C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\windows_events.py:488>>, <ReadSubprocessPipeProto fd=1 pipe=<_ProactorReadPipeTransport fd=2020 read=<_OverlappedFuture pending overlapped=<pending, 0x24dce8a89d0> cb=[_ProactorReadPipeTransport._loop_reading()] created at C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\windows_events.py:488>>>)
1635988954.831 INFO asyncio execute program 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shellous-j1zXeGWZ-py3.10\\Scripts\\python.exe': <_WindowsSubprocessTransport pid=4556 running stdin=<_ProactorWritePipeTransport fd=2204 read=<_OverlappedFuture pending overlapped=<pending, 0x24dce8aaa70> cb=[_ProactorWritePipeTransport._pipe_closed()] created at C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\windows_events.py:465>> stdout=<_ProactorReadPipeTransport fd=2020 read=<_OverlappedFuture pending overlapped=<pending, 0x24dce8a89d0> cb=[_ProactorReadPipeTransport._loop_reading()] created at C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\windows_events.py:488>>>
1635988954.832 INFO shellous Runner._subprocess_exec stepout <Runner 'echo' pid=4556 exit_code=None> ex=None
1635988954.832 INFO shellous Runner._subprocess_spawn stepout <Runner 'echo' pid=4556 exit_code=None> ex=None
1635988954.834 INFO shellous Runner._start stepout <Runner 'echo' pid=4556 exit_code=None> ex=None
1635988954.834 INFO shellous Runner.__aenter__ stepout <Runner 'echo' pid=4556 exit_code=None> ex=None
1635988954.834 INFO shellous read_lines stepin
1635988954.835 INFO shellous write_stream stepin
1635988954.836 INFO shellous write_stream stepout ex=None
1635988954.836 INFO shellous Runner._waiter stepin <Runner 'echo' pid=4556 exit_code=None>
1635988954.876 INFO shellous Runner.__aexit__ stepin <Runner 'echo' pid=4556 exit_code=None> exc_value=CancelledError()
1635988954.877 INFO shellous Runner._finish stepin <Runner 'echo' pid=4556 exit_code=None>
1635988954.877 INFO shellous Runner._kill stepin <Runner 'echo' cancelled pid=4556 exit_code=None>
1635988954.877 INFO shellous Runner.signal <Runner 'echo' cancelled pid=4556 exit_code=None> signal=<Signals.SIGTERM: 15>
1635988954.878 INFO shellous Runner._waiter stepout <Runner 'echo' cancelled pid=4556 exit_code=None> ex=CancelledError()
1635988954.881 INFO shellous harvest_wait cancelled trustee=<Runner 'echo' cancelled pid=4556 exit_code=None> cancel_finish=False ex=GeneratorExit()
1635988954.885 INFO shellous read_lines stepout ex=GeneratorExit()
1635988954.885 INFO shellous Runner._kill stepout <Runner 'echo' cancelled pid=4556 exit_code=None> ex=GeneratorExit()
1635988954.885 INFO shellous Runner._close stepin <Runner 'echo' cancelled pid=4556 exit_code=None>
1635988954.885 CRITICAL shellous Runner._close process still running <Process 4556>
1635988954.886 INFO shellous Runner._close stepout <Runner 'echo' cancelled pid=4556 exit_code=None> ex=GeneratorExit()
1635988954.886 INFO shellous Runner._finish stepout <Runner 'echo' cancelled pid=4556 exit_code=None> ex=GeneratorExit()
1635988954.886 INFO shellous Runner.__aexit__ stepout <Runner 'echo' cancelled pid=4556 exit_code=None> ex=GeneratorExit() exc_value=CancelledError()
1635988954.886 INFO asyncio <_WindowsSubprocessTransport closed pid=4556 running stdin=<_ProactorWritePipeTransport closed> stdout=<_ProactorReadPipeTransport closing fd=2020>> exited with return code 1
1635988954.886 DEBUG asyncio <_ProactorReadPipeTransport closing fd=2020> received EOF
1635988954.892 DEBUG asyncio Close <ProactorEventLoop running=False closed=False debug=True>
PASSED
------------------------------ live log teardown ------------------------------
1635988954.916 DEBUG asyncio Close <ProactorEventLoop running=False closed=False debug=True>
```

**Comment by byllyfish** [comment]
PR #159
