### ISSUE TITLE
test_process_substitution timeout: DefaultChildWatcher issue while running under code coverage

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/shellous#161]
```
________________ ERROR at teardown of test_process_substitution ________________

    def finalizer():
        """Yield again, to finalize."""
    
        async def async_finalizer():
            try:
                await gen_obj.__anext__()
            except StopAsyncIteration:
                pass
            else:
                msg = "Async generator fixture didn't stop."
                msg += "Yield only once."
                raise ValueError(msg)
    
>       loop.run_until_complete(async_finalizer())

../../../Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:139: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:642: in run_until_complete
    return future.result()
../../../Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:131: in async_finalizer
    await gen_obj.__anext__()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @pytest.fixture(autouse=True)
    async def report_orphan_tasks():
        "Make sure that all async tests exit with only a single task running."
    
        # Only run asyncio tests on the main thread. There may be limitations on
        # the childwatcher.
        assert threading.current_thread() is threading.main_thread()
    
        with _check_open_fds():
            yield
            # Close the childwatcher *before* checking for open fd's.
            if sys.platform != "win32":
                cw = asyncio.get_child_watcher()
                if isinstance(cw, DefaultChildWatcher):
                    cw.close()
    
        # Check if any tasks are still running.
        tasks = asyncio.all_tasks()
        if len(tasks) > 1:
            extra_tasks = tasks - {asyncio.current_task()}
>           pytest.fail(f"Orphan tasks still running: {extra_tasks}")
E           Failed: Orphan tasks still running: {<Task pending name='Task-1913' coro=<test_process_substitution() running at /Users/runner/work/shellous/shellous/tests/test_shellous.py:698> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10e8cbf40>()] created at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:424> created at /Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:193>, <Task pending name='cat#procsub' coro=<Runner.run_command() running at /Users/runner/work/shellous/shellous/shellous/runner.py:796> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10e8cbca0>()] created at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:424> cb=[_wait.<locals>._on_completion() at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/tasks.py:513] created at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/tasks.py:361>, <Task pending name='echo#waiter' coro=<Runner._waiter() running at /Users/runner/work/shellous/shellous/shellous/log.py:110> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10e8cb340>()] created at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:424> cb=[_wait.<locals>._on_completion() at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/tasks.py:513] created at /Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/tasks.py:361>}

tests/conftest.py:95: Failed
----------------------------- Captured stderr call -----------------------------

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~ Stack of Thread-153 (123145425272832) ~~~~~~~~~~~~~~~~~~~~~
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/runner/work/shellous/shellous/shellous/watcher.py", line 146, in run
    self._event_loop()
  File "/Users/runner/work/shellous/shellous/shellous/watcher.py", line 168, in _event_loop
    pending = self._kqueue.control(None, 10, 10)

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
------------------------------ Captured log call -------------------------------
INFO     shellous:log.py:102 Runner.__aenter__ stepin <Runner 'cat' pid=None> (macOS-10.16 CPython 3.9.8 asyncio.unix_events._UnixSelectorEventLoop MainThread DefaultChildWatcher)
INFO     shellous:log.py:102 Runner._start stepin <Runner 'cat' pid=None>
INFO     shellous:log.py:102 Runner._subprocess_spawn stepin <Runner 'cat' pid=None>
INFO     shellous:log.py:102 Runner._subprocess_exec stepin <Runner 'cat' pid=None>
INFO     asyncio:base_events.py:1665 execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=8311 running stdin=<_UnixWritePipeTransport fd=23 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=24 polling>>
INFO     shellous:log.py:113 Runner._subprocess_exec stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._subprocess_spawn stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._start stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner.__aenter__ stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:146 copy_bytearray stepin
INFO     shellous:log.py:102 Runner.__aenter__ stepin <Runner 'echo' pid=None> (macOS-10.16 CPython 3.9.8 asyncio.unix_events._UnixSelectorEventLoop MainThread DefaultChildWatcher)
INFO     shellous:log.py:102 Runner._start stepin <Runner 'echo' pid=None>
INFO     shellous:log.py:102 Runner._subprocess_spawn stepin <Runner 'echo' pid=None>
INFO     shellous:log.py:146 write_stream stepin
INFO     shellous:log.py:151 write_stream stepout ex=None
INFO     shellous:log.py:102 Runner._waiter stepin <Runner 'cat' pid=8311 exit_code=None>
INFO     shellous:log.py:102 Runner._subprocess_exec stepin <Runner 'echo' pid=None>
INFO     asyncio:base_events.py:1665 execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=8318 running stdin=<_UnixWritePipeTransport fd=22 idle bufsize=0>>
INFO     shellous:log.py:113 Runner._subprocess_exec stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._subprocess_spawn stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._start stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner.__aenter__ stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:102 Runner.__aexit__ stepin <Runner 'echo' pid=8318 exit_code=None> exc_value=None
INFO     shellous:log.py:102 Runner._finish stepin <Runner 'echo' pid=8318 exit_code=None>
INFO     shellous:log.py:102 Runner._wait stepin <Runner 'echo' pid=8318 exit_code=None>
INFO     shellous:log.py:146 write_stream stepin
INFO     shellous:log.py:151 write_stream stepout ex=None
INFO     shellous:log.py:102 Runner._waiter stepin <Runner 'echo' pid=8318 exit_code=None>
INFO     shellous:util.py:84 os.waitpid returned (0, 0)
INFO     asyncio:unix_events.py:503 <_UnixReadPipeTransport fd=24 polling> was closed by peer
INFO     shellous:util.py:84 os.waitpid returned (8311, 0)
INFO     asyncio:base_subprocess.py:211 <_UnixSubprocessTransport pid=8311 running stdin=<_UnixWritePipeTransport closed fd=23 closed> stdout=<_UnixReadPipeTransport closing fd=24 idle>> exited with return code 0
INFO     shellous:log.py:113 Runner._waiter stepout <Runner 'cat' pid=8311 exit_code=0> ex=None
INFO     shellous:log.py:151 copy_bytearray stepout ex=None
INFO     shellous:log.py:102 Runner.__aexit__ stepin <Runner 'cat' pid=8311 exit_code=0> exc_value=None
INFO     shellous:log.py:102 Runner._finish stepin <Runner 'cat' pid=8311 exit_code=0>
INFO     shellous:log.py:102 Runner._wait stepin <Runner 'cat' pid=8311 exit_code=0>
=================================== FAILURES ===================================
__________________________ test_process_substitution ___________________________

kwargs = {'cat_cmd': Command(args=('/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python', Posi...e=False, writable=False, _start_new_session=False, _preexec_fn=None, pty=False, close_fds=False, audit_callback=None))}
coro = <coroutine object test_process_substitution at 0x10e8bf2c0>
task = <Task pending name='Task-1913' coro=<test_process_substitution() running at /Users/runner/work/shellous/shellous/tests...r/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:193>

    @functools.wraps(func)
    def inner(**kwargs):
        coro = func(**kwargs)
        if coro is not None:
            task = asyncio.ensure_future(coro, loop=_loop)
            try:
>               _loop.run_until_complete(task)

../../../Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:195: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:629: in run_until_complete
    self.run_forever()
../../../hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:596: in run_forever
    self._run_once()
../../../hostedtoolcache/Python/3.9.8/x64/lib/python3.9/asyncio/base_events.py:1854: in _run_once
    event_list = self._selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selectors.KqueueSelector object at 0x10e8cc1f0>, timeout = None

    def select(self, timeout=None):
        timeout = None if timeout is None else max(timeout, 0)
        # If max_ev is 0, kqueue will ignore the timeout. For consistent
        # behavior with the other selector classes, we prevent that here
        # (using max). See https://bugs.python.org/issue29255
        max_ev = max(len(self._fd_to_key), 1)
        ready = []
        try:
>           kev_list = self._selector.control(None, max_ev, timeout)
E           Failed: Timeout >10.0s

../../../hostedtoolcache/Python/3.9.8/x64/lib/python3.9/selectors.py:562: Failed
----------------------------- Captured stderr call -----------------------------

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~ Stack of Thread-153 (123145425272832) ~~~~~~~~~~~~~~~~~~~~~
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/Users/runner/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/runner/work/shellous/shellous/shellous/watcher.py", line 146, in run
    self._event_loop()
  File "/Users/runner/work/shellous/shellous/shellous/watcher.py", line 168, in _event_loop
    pending = self._kqueue.control(None, 10, 10)

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
------------------------------ Captured log call -------------------------------
INFO     shellous:log.py:102 Runner.__aenter__ stepin <Runner 'cat' pid=None> (macOS-10.16 CPython 3.9.8 asyncio.unix_events._UnixSelectorEventLoop MainThread DefaultChildWatcher)
INFO     shellous:log.py:102 Runner._start stepin <Runner 'cat' pid=None>
INFO     shellous:log.py:102 Runner._subprocess_spawn stepin <Runner 'cat' pid=None>
INFO     shellous:log.py:102 Runner._subprocess_exec stepin <Runner 'cat' pid=None>
INFO     asyncio:base_events.py:1665 execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=8311 running stdin=<_UnixWritePipeTransport fd=23 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=24 polling>>
INFO     shellous:log.py:113 Runner._subprocess_exec stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._subprocess_spawn stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._start stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner.__aenter__ stepout <Runner 'cat' pid=8311 exit_code=None> ex=None
INFO     shellous:log.py:146 copy_bytearray stepin
INFO     shellous:log.py:102 Runner.__aenter__ stepin <Runner 'echo' pid=None> (macOS-10.16 CPython 3.9.8 asyncio.unix_events._UnixSelectorEventLoop MainThread DefaultChildWatcher)
INFO     shellous:log.py:102 Runner._start stepin <Runner 'echo' pid=None>
INFO     shellous:log.py:102 Runner._subprocess_spawn stepin <Runner 'echo' pid=None>
INFO     shellous:log.py:146 write_stream stepin
INFO     shellous:log.py:151 write_stream stepout ex=None
INFO     shellous:log.py:102 Runner._waiter stepin <Runner 'cat' pid=8311 exit_code=None>
INFO     shellous:log.py:102 Runner._subprocess_exec stepin <Runner 'echo' pid=None>
INFO     asyncio:base_events.py:1665 execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=8318 running stdin=<_UnixWritePipeTransport fd=22 idle bufsize=0>>
INFO     shellous:log.py:113 Runner._subprocess_exec stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._subprocess_spawn stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner._start stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:113 Runner.__aenter__ stepout <Runner 'echo' pid=8318 exit_code=None> ex=None
INFO     shellous:log.py:102 Runner.__aexit__ stepin <Runner 'echo' pid=8318 exit_code=None> exc_value=None
INFO     shellous:log.py:102 Runner._finish stepin <Runner 'echo' pid=8318 exit_code=None>
INFO     shellous:log.py:102 Runner._wait stepin <Runner 'echo' pid=8318 exit_code=None>
INFO     shellous:log.py:146 write_stream stepin
INFO     shellous:log.py:151 write_stream stepout ex=None
INFO     shellous:log.py:102 Runner._waiter stepin <Runner 'echo' pid=8318 exit_code=None>
INFO     shellous:util.py:84 os.waitpid returned (0, 0)
INFO     asyncio:unix_events.py:503 <_UnixReadPipeTransport fd=24 polling> was closed by peer
INFO     shellous:util.py:84 os.waitpid returned (8311, 0)
INFO     asyncio:base_subprocess.py:211 <_UnixSubprocessTransport pid=8311 running stdin=<_UnixWritePipeTransport closed fd=23 closed> stdout=<_UnixReadPipeTransport closing fd=24 idle>> exited with return code 0
INFO     shellous:log.py:113 Runner._waiter stepout <Runner 'cat' pid=8311 exit_code=0> ex=None
INFO     shellous:log.py:151 copy_bytearray stepout ex=None
INFO     shellous:log.py:102 Runner.__aexit__ stepin <Runner 'cat' pid=8311 exit_code=0> exc_value=None
INFO     shellous:log.py:102 Runner._finish stepin <Runner 'cat' pid=8311 exit_code=0>
INFO     shellous:log.py:102 Runner._wait stepin <Runner 'cat' pid=8311 exit_code=0>
=============================== warnings summary ===============================
tests/test_shellous.py::test_bulk
  /Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object test_process_substitution at 0x10e8bf2c0>
  
  Traceback (most recent call last):
    File "/Users/runner/work/shellous/shellous/tests/test_shellous.py", line 698, in test_process_substitution
      result = await cmd
    File "/Users/runner/work/shellous/shellous/shellous/runner.py", line 797, in run_command
      await redir.copy_bytearray(stream, output_bytes)
    File "/Users/runner/work/shellous/shellous/shellous/log.py", line 110, in _method_wrapper
      return await func(*args, **kwargs)
    File "/Users/runner/work/shellous/shellous/shellous/runner.py", line 674, in __aexit__
      suppress = await self._finish(exc_value)
    File "/Users/runner/work/shellous/shellous/shellous/log.py", line 110, in _method_wrapper
      return await func(*args, **kwargs)
  RuntimeError: coroutine ignored GeneratorExit
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
```

**Comment by byllyfish** [comment]
Closing. I think the GeneratorExit issue is fixed; there have been many changes to DefaultChildWatcher since this bug appeared.
