### ISSUE TITLE
pypy-3.8: Windows: test_broken_pipe: Fatal write error on pipe transport ... [WinError 997] Overlapped I/O operation is in progress

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/shellous#187]
```
tests/test_shellous.py::test_broken_pipe 
------------------------------- live log setup --------------------------------
1638911239.369 DEBUG asyncio Using proactor: IocpProactor
1638911239.371 DEBUG asyncio Using proactor: IocpProactor
1638911239.372 DEBUG asyncio Close <ProactorEventLoop running=False closed=False debug=True>
-------------------------------- live log call --------------------------------
1638911239.384 INFO shellous Runner.__aenter__ stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=None> (Windows-10 PyPy 3.8.12 asyncio.windows_events.ProactorEventLoop MainThread)
1638911239.385 INFO shellous Runner._start stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=None>
1638911239.385 INFO shellous Runner._subprocess_spawn stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=None>
1638911239.388 INFO shellous Runner._subprocess_exec stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=None>
1638911239.389 DEBUG asyncio execute program 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shellous-j1zXeGWZ-py3.8\\Scripts\\python.exe' stdin=<pipe> stdout=<pipe> stderr=<Redirect.DEVNULL: -3>
1638911239.396 DEBUG asyncio process 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shellous-j1zXeGWZ-py3.8\\Scripts\\python.exe' created: pid 6948
1638911239.399 DEBUG asyncio Write pipe 1328 connected: (<_ProactorWritePipeTransport fd=1328 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744610> cb=[_ProactorWritePipeTransport._pipe_closed()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>>, <WriteSubprocessPipeProto fd=0 pipe=<_ProactorWritePipeTransport fd=1328 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744610> cb=[_ProactorWritePipeTransport._pipe_closed()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>>>)
1638911239.403 DEBUG asyncio Read pipe 1508 connected: (<_ProactorReadPipeTransport fd=1508 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744730> cb=[_ProactorReadPipeTransport._loop_reading()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>>, <ReadSubprocessPipeProto fd=1 pipe=<_ProactorReadPipeTransport fd=1508 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744730> cb=[_ProactorReadPipeTransport._loop_reading()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>>>)
1638911239.405 INFO asyncio execute program 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shellous-j1zXeGWZ-py3.8\\Scripts\\python.exe': <_WindowsSubprocessTransport pid=6948 running stdin=<_ProactorWritePipeTransport fd=1328 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744610> cb=[_ProactorWritePipeTransport._pipe_closed()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>> stdout=<_ProactorReadPipeTransport fd=1508 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744730> cb=[_ProactorReadPipeTransport._loop_reading()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>>>
1638911239.406 INFO shellous Runner._subprocess_exec stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None> ex=None
1638911239.408 INFO shellous Runner._subprocess_spawn stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None> ex=None
1638911239.410 INFO shellous Runner._start stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None> ex=None
1638911239.410 INFO shellous Runner.__aenter__ stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None> ex=None
1638911239.411 INFO shellous copy_bytearray stepin
1638911239.412 INFO shellous write_stream stepin
1638911239.413 DEBUG asyncio <_ProactorWritePipeTransport fd=1328 read=<_OverlappedFuture pending overlapped=<pending, 0x24f0d744610> cb=[_ProactorWritePipeTransport._pipe_closed()] created at D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py:465>>: Fatal write error on pipe transport
Traceback (most recent call last):
  File "D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\asyncio\windows_events.py", line 534, in send
    ov.WriteFile(conn.fileno(), buf)
  File "D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\_overlapped.py", line 405, in WriteFile
    RaiseFromWindowsErr(self.error)
  File "D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\_winapi.py", line 51, in RaiseFromWindowsErr
    raise_WinError(type)
  File "D:\a\_temp\ba58fb03-b9f3-4a72-b8ce-17ebdc9ec183\pypy-c-jit-104008-61cbdf45d566-win64\Lib\_winapi.py", line 36, in raise_WinError
    raise excep
OSError: [WinError 997] Overlapped I/O operation is in progress
1638911239.415 INFO shellous Runner._waiter stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None>
1638911239.417 INFO shellous write_stream stepout ex=None
1638911239.486 ERROR asyncio GetQueuedCompletionStatus() returned an unexpected event
status: "err=109 transferred=<cdata 'unsigned long[1]' owning 4 bytes> key=0x0 address=0x24f0d743e60"
1638911239.487 DEBUG asyncio <_ProactorReadPipeTransport fd=1508> received EOF
1638911239.488 INFO shellous copy_bytearray stepout ex=None
1638911239.489 INFO shellous Runner.__aexit__ stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None> exc_value=None
1638911239.489 INFO shellous Runner._finish stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None>
1638911239.490 INFO shellous Runner._wait stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=None>
1638911239.495 INFO asyncio <_WindowsSubprocessTransport pid=6948 running stdin=<_ProactorWritePipeTransport closed> stdout=<_ProactorReadPipeTransport closed>> exited with return code 0
1638911239.497 INFO shellous Runner._waiter stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=0> ex=None
1638911239.499 INFO shellous Runner._wait stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=0> ex=None
1638911239.499 INFO shellous Runner._close stepin <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=0>
1638911239.502 DEBUG shellous 'Task-384' exception consumed OSError(None, 'Overlapped I/O operation is in progress', None, 997)
1638911239.503 INFO shellous Runner._close stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=0> ex=OSError(None, 'Overlapped I/O operation is in progress', None, 997)
1638911239.503 INFO shellous Runner._finish stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=0> ex=OSError(None, 'Overlapped I/O operation is in progress', None, 997)
1638911239.503 INFO shellous Runner.__aexit__ stepout <Runner '...zXeGWZ-py3.8\\Scripts\\python.exe' pid=6948 exit_code=0> ex=OSError(None, 'Overlapped I/O operation is in progress', None, 997) exc_value=None
FAILED
------------------------------ live log teardown ------------------------------
1638911240.112 DEBUG asyncio Close <ProactorEventLoop running=False closed=False debug=True>
```

**Comment by byllyfish** [comment]
Will try later with pypy-3.9.
