### ISSUE TITLE
3.10-dev,macos-latest:  Random failure in test_broken_pipe_in_failed_pipeline 

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/shellous#32]
ResultError. Not reporting BrokenPipeError as expected.

tests/test_shellous.py::test_broken_pipe_in_failed_pipeline 
-------------------------------- live log call ---------------------------------
1629923567.884 INFO PipeRunner entering 'cat|echo'
1629923567.886 INFO PipeRunner entered 'cat|echo' ex=None
1629923567.886 INFO PipeRunner exiting 'cat|echo' exc_value=None
1629923567.886 INFO Runner entering <Runner 'cat' pid=None> (macOS-10.15.7 CPython 3.10.0rc1 asyncio.unix_events._UnixSelectorEventLoop ThreadedChildWatcher)
1629923567.892 INFO Runner entering <Runner 'echo' pid=None> (macOS-10.15.7 CPython 3.10.0rc1 asyncio.unix_events._UnixSelectorEventLoop ThreadedChildWatcher)
1629923567.904 INFO execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/bin/python': <_UnixSubprocessTransport pid=3468 running stdin=<_UnixWritePipeTransport fd=14 idle bufsize=0>>
1629923567.906 INFO Runner entered <Runner 'cat' pid=3468 exit_code=None> ex=None
1629923567.906 INFO Runner exiting <Runner 'cat' pid=3468 exit_code=None> exc_value=None
1629923567.906 INFO Runner._wait stepin <Runner 'cat' pid=3468 exit_code=None>
1629923567.907 INFO execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/bin/python': <_UnixSubprocessTransport pid=3469 running stdout=<_UnixReadPipeTransport fd=11 polling>>
Traceback (most recent call last):
1629923567.907 INFO Runner entered <Runner 'echo' pid=3469 exit_code=None> ex=None
  File "/Users/runner/work/shellous/shellous/tests/python_script.py", line 24, in <module>
1629923567.956 INFO <_UnixReadPipeTransport fd=11 polling> was closed by peer
    _write(data)
1629923567.963 INFO Runner exiting <Runner 'echo' pid=3469 exit_code=None> exc_value=None
  File "/Users/runner/work/shellous/shellous/tests/python_script.py", line 15, in _write
1629923567.963 INFO Runner._wait stepin <Runner 'echo' pid=3469 exit_code=None>
    sys.stdout.buffer.write(data)
1629923567.965 INFO <_UnixSubprocessTransport pid=3468 running stdin=<_UnixWritePipeTransport closed fd=14 closed>> exited with return code 120
BrokenPipeError: [Errno 32] Broken pipe
1629923567.965 INFO <_UnixSubprocessTransport pid=3469 running stdout=<_UnixReadPipeTransport closed fd=11 closed>> exited with return code 7
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
1629923567.966 INFO _feed_writer ex=BrokenPipeError(32, 'Broken pipe')
BrokenPipeError: [Errno 32] Broken pipe
1629923567.967 INFO Runner._wait stepout <Runner 'cat' pid=3468 exit_code=120> ex=None
1629923567.967 INFO Runner._close stepin <Runner 'cat' pid=3468 exit_code=120>
1629923567.968 INFO Runner._wait stepout <Runner 'echo' pid=3469 exit_code=7> ex=None
1629923567.968 INFO Runner._close stepin <Runner 'echo' pid=3469 exit_code=7>
1629923567.968 INFO Runner._close stepout <Runner 'echo' pid=3469 exit_code=7> ex=None
1629923567.968 INFO Runner exited <Runner 'echo' pid=3469 exit_code=7> ex=None exc_value=None suppress=False
1629923567.970 INFO gather_collect cancelling 1 of 2 tasks ret_ex=True trustee=<shellous.runner.PipeRunner object at 0x106b5e350>
1629923567.971 WARNING gather_collect itself cancelled ret_ex=False trustee=<Runner 'cat' pid=3468 exit_code=120>
1629923567.972 INFO Runner._close stepout <Runner 'cat' pid=3468 exit_code=120> ex=CancelledError()
1629923567.972 WARNING Runner cancelled inside _finish <Runner 'cat' pid=3468 exit_code=120>
1629923567.972 INFO Runner exited <Runner 'cat' pid=3468 exit_code=120> ex=None exc_value=None suppress=False
1629923567.973 INFO PipeRunner.wait results=[ResultError(Result(output_bytes=None, exit_code=120, cancelled=False, encoding='utf-8', extra=None)), ResultError(Result(output_bytes=b'abc', exit_code=7, cancelled=False, encoding='utf-8', extra=None))]
1629923567.973 INFO PipeRunner exited 'cat|echo' ex=None
FAILED

**Comment by byllyfish** [comment]
Another failure, this time while doing code coverage on ubuntu-latest, Python 3.9.

_____________________ test_broken_pipe_in_failed_pipeline ______________________

cat_cmd = Command(args=('/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python', PosixPath('tests/python_s...utf-8', return_result=False, exit_codes=None, cancel_timeout=3.0, cancel_signal=<Signals.SIGTERM: 15>, alt_name='cat'))
echo_cmd = Command(args=('/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python', PosixPath('tests/python_s...tf-8', return_result=False, exit_codes=None, cancel_timeout=3.0, cancel_signal=<Signals.SIGTERM: 15>, alt_name='echo'))

    @pytest.mark.xfail(_latent_bug(), reason="latent bug")
    async def test_broken_pipe_in_failed_pipeline(cat_cmd, echo_cmd):
        "Test broken pipe error within a pipeline; last command fails."
        data = b"c" * PIPE_MAX_SIZE
        echo = echo_cmd.env(SHELLOUS_EXIT_CODE=7)
    
        with pytest.raises(BrokenPipeError):
>           await (data | cat_cmd | echo("abc"))

tests/test_shellous.py:297: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
shellous/runner.py:629: in run_pipe
    return run.result()
shellous/runner.py:442: in result
    return make_result(self.pipe, self.results)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = Pipeline(commands=(Command(args=('/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python', PosixP...-8', return_result=False, exit_codes=None, cancel_timeout=3.0, cancel_signal=<Signals.SIGTERM: 15>, alt_name='echo'))))
result = Result(output_bytes=b'abc', exit_code=120, cancelled=False, encoding='utf-8', extra=(PipeResult(exit_code=120, cancelled=False), PipeResult(exit_code=7, cancelled=False)))

    def make_result(command, result):
        """Convert list of results into a single pipe result.
    
        `result` can be a list of Result, ResultError or another Exception.
        """
    
        if isinstance(result, list):
            # Check result list for other exceptions.
            other_ex = [
                ex
                for ex in result
                if isinstance(ex, Exception) and not isinstance(ex, ResultError)
            ]
            if other_ex:
                # Re-raise other exception here.
                raise other_ex[0]
    
            # Everything in result is now either a Result or ResultError.
            key_result = _find_key_result(result)
            last = _get_result(result[-1])
    
            result = Result(
                last.output_bytes,
                key_result.exit_code,
                key_result.cancelled,
                last.encoding,
                tuple(PipeResult.from_result(r) for r in result),
            )
    
        assert isinstance(result, Result)
    
        exit_codes = command.options.exit_codes or {0}
        if result.exit_code not in exit_codes:
>           raise ResultError(result)
E           shellous.result.ResultError: Result(output_bytes=b'abc', exit_code=120, cancelled=False, encoding='utf-8', extra=(PipeResult(exit_code=120, cancelled=False), PipeResult(exit_code=7, cancelled=False)))

shellous/result.py:90: ResultError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/runner/work/shellous/shellous/tests/python_script.py", line 24, in <module>
    _write(data)
  File "/home/runner/work/shellous/shellous/tests/python_script.py", line 15, in _write
    sys.stdout.buffer.write(data)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
------------------------------ Captured log call -------------------------------
WARNING  shellous:runner.py:358 Runner cancelled inside _finish <Runner 'cat' pid=2561 exit_code=120>
=========================== short test summary info ============================
FAILED tests/test_shellous.py::test_broken_pipe_in_failed_pipeline - shellous...
============= 1 failed, 156 passed, 5 skipped, 3 xfailed in 12.83s =============

**Comment by byllyfish** [comment]
Fixed in 0.3.0
