### ISSUE TITLE
FastChildWatcher on Linux fails; CRITICAL Runner._close process still running <Process 4049>

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/shellous#85]
```
tests/test_shellous.py::test_pipe_exception_in_async_iter 
-------------------------------- live log setup --------------------------------
1632866631.696 DEBUG Using selector: EpollSelector
1632866631.696 DEBUG Using selector: EpollSelector
1632866631.697 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
-------------------------------- live log call ---------------------------------
1632866631.700 INFO PipeRunner.__aenter__ stepin <PipeRunner 'env|tr'>
1632866631.700 INFO PipeRunner._start stepin <PipeRunner 'env|tr'>
1632866631.700 INFO PipeRunner._setup_capturing stepin <PipeRunner 'env|tr'>
1632866631.702 INFO Runner.__aenter__ stepin <Runner 'env' pid=None> (Linux-5.8.0-1041-azure-x86_64-with-glibc2.31 CPython 3.10.0rc2 asyncio.unix_events._UnixSelectorEventLoop MainThread FastChildWatcher)
1632866631.702 INFO Runner._start stepin <Runner 'env' pid=None>
1632866631.703 INFO Runner._subprocess_spawn stepin <Runner 'env' pid=None>
1632866631.703 DEBUG execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.10/bin/python' stdin=<pipe> stdout=10 stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
1632866631.704 DEBUG process '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.10/bin/python' created: pid 4048
1632866631.705 INFO Runner.__aenter__ stepin <Runner 'tr' pid=None> (Linux-5.8.0-1041-azure-x86_64-with-glibc2.31 CPython 3.10.0rc2 asyncio.unix_events._UnixSelectorEventLoop MainThread FastChildWatcher)
1632866631.705 INFO Runner._start stepin <Runner 'tr' pid=None>
1632866631.705 INFO Runner._subprocess_spawn stepin <Runner 'tr' pid=None>
1632866631.706 DEBUG execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.10/bin/python' stdin=9 stdout=<pipe> stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
1632866631.707 DEBUG process '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.10/bin/python' created: pid 4049
1632866631.709 DEBUG Write pipe 13 connected: (<_UnixWritePipeTransport fd=13 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=13 idle bufsize=0>>)
1632866631.709 DEBUG Read pipe 12 connected: (<_UnixReadPipeTransport fd=12 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=12 polling>>)
1632866631.710 INFO execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.10/bin/python': <_UnixSubprocessTransport pid=4048 running stdin=<_UnixWritePipeTransport fd=13 idle bufsize=0>>
1632866631.710 INFO Runner._subprocess_spawn stepout <Runner 'env' pid=4048 exit_code=None> ex=None
1632866631.710 INFO Runner._start stepout <Runner 'env' pid=4048 exit_code=None> ex=None
1632866631.710 INFO Runner.__aenter__ stepout <Runner 'env' pid=4048 exit_code=None> ex=None
1632866631.711 INFO Runner.__aexit__ stepin <Runner 'env' pid=4048 exit_code=None> exc_value=None
1632866631.711 INFO Runner._finish stepin <Runner 'env' pid=4048 exit_code=None>
1632866631.711 INFO Runner._wait stepin <Runner 'env' pid=4048 exit_code=None>
1632866631.711 INFO execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.10/bin/python': <_UnixSubprocessTransport pid=4049 running stdout=<_UnixReadPipeTransport fd=12 polling>>
1632866631.712 INFO Runner._subprocess_spawn stepout <Runner 'tr' pid=4049 exit_code=None> ex=None
1632866631.712 INFO Runner._start stepout <Runner 'tr' pid=4049 exit_code=None> ex=None
1632866631.713 INFO Runner.__aenter__ stepout <Runner 'tr' pid=4049 exit_code=None> ex=None
1632866631.713 INFO Runner.__aexit__ stepin <Runner 'tr' pid=4049 exit_code=None> exc_value=None
1632866631.713 INFO Runner._finish stepin <Runner 'tr' pid=4049 exit_code=None>
1632866631.713 INFO Runner._wait stepin <Runner 'tr' pid=4049 exit_code=None>
1632866631.714 INFO write_stream stepin
1632866631.715 INFO write_stream stepout ex=None
1632866631.716 INFO Runner._waiter stepin <Runner 'env' pid=4048 exit_code=None>
1632866631.716 INFO Runner._waiter stepin <Runner 'tr' pid=4049 exit_code=None>
1632866631.722 INFO PipeRunner._setup_capturing stepout <PipeRunner 'env|tr'> ex=None
1632866631.722 INFO PipeRunner._start stepout <PipeRunner 'env|tr'> ex=None
1632866631.722 INFO PipeRunner.__aenter__ stepout <PipeRunner 'env|tr'> ex=None
1632866631.723 INFO read_lines stepin
1632866631.746 INFO PipeRunner.__aexit__ stepin <PipeRunner 'env|tr'> exc_value=ValueError(1)
1632866631.746 INFO PipeRunner._finish stepin <PipeRunner 'env|tr'>
1632866631.747 INFO PipeRunner._wait stepin <PipeRunner 'env|tr'>
1632866631.747 INFO PipeRunner.wait killing pipe <PipeRunner 'env|tr'>
1632866631.748 DEBUG process 4048 exited with returncode 0
1632866631.748 INFO harvest_wait cancelled trustee=<Runner 'env' pid=4048 exit_code=None> cancel_finish=False
1632866631.749 INFO harvest_wait cancelled trustee=<Runner 'tr' pid=4049 exit_code=None> cancel_finish=False
1632866631.750 INFO <_UnixSubprocessTransport pid=4048 running stdin=<_UnixWritePipeTransport closed fd=13 closed>> exited with return code 0
1632866631.751 INFO Runner._waiter stepout <Runner 'env' pid=4048 exit_code=0> ex=CancelledError()
1632866631.752 INFO Runner._waiter stepout <Runner 'tr' pid=4049 exit_code=None> ex=CancelledError()
1632866631.753 INFO read_lines stepout ex=GeneratorExit()
1632866631.753 INFO Runner.wait cancelled <Runner 'env' pid=4048 exit_code=0>
1632866631.753 INFO Runner._kill stepin <Runner 'env' cancelled pid=4048 exit_code=0>
1632866631.753 INFO Runner._kill stepout <Runner 'env' cancelled pid=4048 exit_code=0> ex=CancelledError()
1632866631.754 INFO Runner._wait stepout <Runner 'env' cancelled pid=4048 exit_code=0> ex=None
1632866631.754 INFO Runner._close stepin <Runner 'env' cancelled pid=4048 exit_code=0>
1632866631.754 INFO Runner.wait cancelled <Runner 'tr' pid=4049 exit_code=None>
1632866631.755 INFO Runner._kill stepin <Runner 'tr' cancelled pid=4049 exit_code=None>
1632866631.755 INFO Runner.signal <Runner 'tr' cancelled pid=4049 exit_code=None> signal=<Signals.SIGTERM: 15>
1632866631.757 INFO <_UnixReadPipeTransport fd=12 polling> was closed by peer
1632866631.757 INFO Runner._close stepout <Runner 'env' cancelled pid=4048 exit_code=0> ex=None
1632866631.757 INFO Runner._finish stepout <Runner 'env' cancelled pid=4048 exit_code=0> ex=None
1632866631.758 INFO Runner.__aexit__ stepout <Runner 'env' cancelled pid=4048 exit_code=0> ex=None exc_value=None
1632866631.758 INFO harvest_wait cancelled trustee=<Runner 'tr' cancelled pid=4049 exit_code=None> cancel_finish=False
1632866631.759 WARNING Runner.kill <Runner 'tr' cancelled pid=4049 exit_code=None> (ex)=CancelledError()
1632866631.759 INFO Runner._kill_wait stepin <Runner 'tr' cancelled pid=4049 exit_code=None>
1632866634.765 INFO harvest_wait timed out trustee=<Runner 'tr' cancelled pid=4049 exit_code=None>
1632866634.765 ERROR <Runner 'tr' cancelled pid=4049 exit_code=None> failed to kill process <Process 4049>
1632866634.765 INFO Runner._kill_wait stepout <Runner 'tr' cancelled pid=4049 exit_code=None> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.766 INFO Runner._kill stepout <Runner 'tr' cancelled pid=4049 exit_code=None> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.766 INFO Runner._wait stepout <Runner 'tr' cancelled pid=4049 exit_code=None> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.766 INFO Runner._close stepin <Runner 'tr' cancelled pid=4049 exit_code=None>
1632866634.766 CRITICAL Runner._close process still running <Process 4049>
1632866634.767 INFO Runner._close stepout <Runner 'tr' cancelled pid=4049 exit_code=None> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.767 INFO Runner._finish stepout <Runner 'tr' cancelled pid=4049 exit_code=None> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.767 INFO Runner.__aexit__ stepout <Runner 'tr' cancelled pid=4049 exit_code=None> ex=RuntimeError('Unable to kill process <Process 4049>') exc_value=None
1632866634.767 INFO PipeRunner._wait stepout <PipeRunner 'env|tr'> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.767 INFO PipeRunner._finish stepout <PipeRunner 'env|tr'> ex=RuntimeError('Unable to kill process <Process 4049>')
1632866634.768 INFO PipeRunner.__aexit__ stepout <PipeRunner 'env|tr'> ex=RuntimeError('Unable to kill process <Process 4049>') exc_value=ValueError(1)
FAILED
------------------------------ live log teardown -------------------------------
1632866634.946 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
```

**Comment by byllyfish** [comment]
Another case:

```
tests/test_shellous.py::test_pipe_with_exception_in_middle 
-------------------------------- live log setup --------------------------------
1632866557.216 DEBUG Using selector: EpollSelector
1632866557.217 DEBUG Using selector: EpollSelector
1632866557.217 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
-------------------------------- live log call ---------------------------------
1632866557.220 INFO PipeRunner.__aenter__ stepin <PipeRunner 'env|tr'>
1632866557.220 INFO PipeRunner._start stepin <PipeRunner 'env|tr'>
1632866557.221 INFO PipeRunner._setup_capturing stepin <PipeRunner 'env|tr'>
1632866557.222 INFO Runner.__aenter__ stepin <Runner 'env' pid=None> (Linux-5.8.0-1041-azure-x86_64-with-glibc2.31 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread FastChildWatcher)
1632866557.222 INFO Runner._start stepin <Runner 'env' pid=None>
1632866557.223 INFO Runner._subprocess_spawn stepin <Runner 'env' pid=None>
1632866557.223 DEBUG execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' stdin=<pipe> stdout=10 stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
1632866557.226 DEBUG process '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' created: pid 3770
1632866557.227 INFO Runner.__aenter__ stepin <Runner 'tr' pid=None> (Linux-5.8.0-1041-azure-x86_64-with-glibc2.31 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread FastChildWatcher)
1632866557.227 INFO Runner._start stepin <Runner 'tr' pid=None>
1632866557.228 INFO Runner._subprocess_spawn stepin <Runner 'tr' pid=None>
1632866557.228 DEBUG execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' stdin=9 stdout=<pipe> stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
1632866557.240 DEBUG process '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' created: pid 3771
1632866557.242 DEBUG Write pipe 13 connected: (<_UnixWritePipeTransport fd=13 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=13 idle bufsize=0>>)
1632866557.243 DEBUG Read pipe 12 connected: (<_UnixReadPipeTransport fd=12 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=12 polling>>)
1632866557.244 INFO execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python': <_UnixSubprocessTransport pid=3770 running stdin=<_UnixWritePipeTransport fd=13 idle bufsize=0>>
1632866557.245 INFO Runner._subprocess_spawn stepout <Runner 'env' pid=3770 exit_code=None> ex=None
1632866557.246 INFO Runner._start stepout <Runner 'env' pid=3770 exit_code=None> ex=None
1632866557.246 INFO Runner.__aenter__ stepout <Runner 'env' pid=3770 exit_code=None> ex=None
1632866557.247 INFO Runner.__aexit__ stepin <Runner 'env' pid=3770 exit_code=None> exc_value=None
1632866557.247 INFO Runner._finish stepin <Runner 'env' pid=3770 exit_code=None>
1632866557.248 INFO Runner._wait stepin <Runner 'env' pid=3770 exit_code=None>
1632866557.249 INFO execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python': <_UnixSubprocessTransport pid=3771 running stdout=<_UnixReadPipeTransport fd=12 polling>>
1632866557.250 INFO Runner._subprocess_spawn stepout <Runner 'tr' pid=3771 exit_code=None> ex=None
1632866557.251 INFO Runner._start stepout <Runner 'tr' pid=3771 exit_code=None> ex=None
1632866557.251 INFO Runner.__aenter__ stepout <Runner 'tr' pid=3771 exit_code=None> ex=None
1632866557.252 INFO Runner.__aexit__ stepin <Runner 'tr' pid=3771 exit_code=None> exc_value=None
1632866557.252 INFO Runner._finish stepin <Runner 'tr' pid=3771 exit_code=None>
1632866557.253 INFO Runner._wait stepin <Runner 'tr' pid=3771 exit_code=None>
1632866557.253 INFO write_stream stepin
1632866557.260 INFO write_stream stepout ex=None
1632866557.261 INFO Runner._waiter stepin <Runner 'env' pid=3770 exit_code=None>
1632866557.262 INFO Runner._waiter stepin <Runner 'tr' pid=3771 exit_code=None>
1632866557.263 INFO PipeRunner._setup_capturing stepout <PipeRunner 'env|tr'> ex=None
1632866557.264 INFO PipeRunner._start stepout <PipeRunner 'env|tr'> ex=None
1632866557.264 INFO PipeRunner.__aenter__ stepout <PipeRunner 'env|tr'> ex=None
1632866557.264 INFO PipeRunner.__aexit__ stepin <PipeRunner 'env|tr'> exc_value=ValueError(1)
1632866557.265 INFO PipeRunner._finish stepin <PipeRunner 'env|tr'>
1632866557.265 INFO PipeRunner._wait stepin <PipeRunner 'env|tr'>
1632866557.266 INFO PipeRunner.wait killing pipe <PipeRunner 'env|tr'>
1632866557.267 INFO harvest_wait cancelled trustee=<Runner 'env' pid=3770 exit_code=None> cancel_finish=False
1632866557.268 INFO harvest_wait cancelled trustee=<Runner 'tr' pid=3771 exit_code=None> cancel_finish=False
1632866557.268 DEBUG process 3770 exited with returncode 0
1632866557.269 INFO Runner._waiter stepout <Runner 'env' pid=3770 exit_code=None> ex=CancelledError()
1632866557.269 INFO Runner._waiter stepout <Runner 'tr' pid=3771 exit_code=None> ex=CancelledError()
1632866557.270 INFO <_UnixSubprocessTransport pid=3770 running stdin=<_UnixWritePipeTransport closed fd=13 closed>> exited with return code 0
1632866557.272 INFO Runner.wait cancelled <Runner 'env' pid=3770 exit_code=0>
1632866557.273 INFO Runner._kill stepin <Runner 'env' cancelled pid=3770 exit_code=0>
1632866557.273 INFO Runner._kill stepout <Runner 'env' cancelled pid=3770 exit_code=0> ex=CancelledError()
1632866557.273 INFO Runner._wait stepout <Runner 'env' cancelled pid=3770 exit_code=0> ex=None
1632866557.274 INFO Runner._close stepin <Runner 'env' cancelled pid=3770 exit_code=0>
1632866557.275 INFO Runner.wait cancelled <Runner 'tr' pid=3771 exit_code=None>
1632866557.275 INFO Runner._kill stepin <Runner 'tr' cancelled pid=3771 exit_code=None>
1632866557.276 INFO Runner.signal <Runner 'tr' cancelled pid=3771 exit_code=None> signal=<Signals.SIGTERM: 15>
1632866557.278 INFO <_UnixReadPipeTransport fd=12 polling> was closed by peer
1632866557.279 INFO Runner._close stepout <Runner 'env' cancelled pid=3770 exit_code=0> ex=None
1632866557.279 INFO Runner._finish stepout <Runner 'env' cancelled pid=3770 exit_code=0> ex=None
1632866557.279 INFO Runner.__aexit__ stepout <Runner 'env' cancelled pid=3770 exit_code=0> ex=None exc_value=None
1632866557.280 INFO harvest_wait cancelled trustee=<Runner 'tr' cancelled pid=3771 exit_code=None> cancel_finish=False
1632866557.281 WARNING Runner.kill <Runner 'tr' cancelled pid=3771 exit_code=None> (ex)=CancelledError()
1632866557.281 INFO Runner._kill_wait stepin <Runner 'tr' cancelled pid=3771 exit_code=None>
1632866560.285 INFO harvest_wait timed out trustee=<Runner 'tr' cancelled pid=3771 exit_code=None>
1632866560.285 ERROR <Runner 'tr' cancelled pid=3771 exit_code=None> failed to kill process <Process 3771>
1632866560.285 INFO Runner._kill_wait stepout <Runner 'tr' cancelled pid=3771 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.285 INFO Runner._kill stepout <Runner 'tr' cancelled pid=3771 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.286 INFO Runner._wait stepout <Runner 'tr' cancelled pid=3771 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.286 INFO Runner._close stepin <Runner 'tr' cancelled pid=3771 exit_code=None>
1632866560.286 CRITICAL Runner._close process still running <Process 3771>
1632866560.286 INFO Runner._close stepout <Runner 'tr' cancelled pid=3771 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.286 INFO Runner._finish stepout <Runner 'tr' cancelled pid=3771 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.286 INFO Runner.__aexit__ stepout <Runner 'tr' cancelled pid=3771 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3771>') exc_value=None
1632866560.287 INFO PipeRunner._wait stepout <PipeRunner 'env|tr'> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.287 INFO PipeRunner._finish stepout <PipeRunner 'env|tr'> ex=RuntimeError('Unable to kill process <Process 3771>')
1632866560.287 INFO PipeRunner.__aexit__ stepout <PipeRunner 'env|tr'> ex=RuntimeError('Unable to kill process <Process 3771>') exc_value=ValueError(1)
FAILED
------------------------------ live log teardown -------------------------------
1632866560.454 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
```

**Comment by byllyfish** [comment]
Another case:

```
tests/test_shellous.py::test_broken_pipe_in_failed_pipeline 
-------------------------------- live log setup --------------------------------
1632866561.255 DEBUG Using selector: EpollSelector
1632866561.256 DEBUG Using selector: EpollSelector
1632866561.256 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
-------------------------------- live log call ---------------------------------
1632866561.260 INFO PipeRunner.__aenter__ stepin <PipeRunner 'cat|echo'>
1632866561.260 INFO PipeRunner._start stepin <PipeRunner 'cat|echo'>
1632866561.261 INFO PipeRunner._start stepout <PipeRunner 'cat|echo'> ex=None
1632866561.261 INFO PipeRunner.__aenter__ stepout <PipeRunner 'cat|echo'> ex=None
1632866561.261 INFO PipeRunner.__aexit__ stepin <PipeRunner 'cat|echo'> exc_value=None
1632866561.262 INFO PipeRunner._finish stepin <PipeRunner 'cat|echo'>
1632866561.262 INFO PipeRunner._wait stepin <PipeRunner 'cat|echo'>
1632866561.262 INFO Runner.__aenter__ stepin <Runner 'cat' pid=None> (Linux-5.8.0-1041-azure-x86_64-with-glibc2.31 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread FastChildWatcher)
1632866561.262 INFO Runner._start stepin <Runner 'cat' pid=None>
1632866561.263 INFO Runner._subprocess_spawn stepin <Runner 'cat' pid=None>
1632866561.263 DEBUG execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' stdin=<pipe> stdout=10 stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
1632866561.266 DEBUG process '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' created: pid 3782
1632866561.267 INFO Runner.__aenter__ stepin <Runner 'echo' pid=None> (Linux-5.8.0-1041-azure-x86_64-with-glibc2.31 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread FastChildWatcher)
1632866561.267 INFO Runner._start stepin <Runner 'echo' pid=None>
1632866561.268 INFO Runner._subprocess_spawn stepin <Runner 'echo' pid=None>
1632866561.268 DEBUG execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' stdin=9 stdout=<pipe> stderr=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
1632866561.271 DEBUG process '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python' created: pid 3783
1632866561.273 DEBUG Write pipe 13 connected: (<_UnixWritePipeTransport fd=13 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=13 idle bufsize=0>>)
1632866561.273 DEBUG Read pipe 12 connected: (<_UnixReadPipeTransport fd=12 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=12 polling>>)
1632866561.274 INFO execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python': <_UnixSubprocessTransport pid=3782 running stdin=<_UnixWritePipeTransport fd=13 idle bufsize=0>>
1632866561.274 INFO Runner._subprocess_spawn stepout <Runner 'cat' pid=3782 exit_code=None> ex=None
1632866561.275 INFO Runner._start stepout <Runner 'cat' pid=3782 exit_code=None> ex=None
1632866561.275 INFO Runner.__aenter__ stepout <Runner 'cat' pid=3782 exit_code=None> ex=None
1632866561.275 INFO Runner.__aexit__ stepin <Runner 'cat' pid=3782 exit_code=None> exc_value=None
1632866561.275 INFO Runner._finish stepin <Runner 'cat' pid=3782 exit_code=None>
1632866561.275 INFO Runner._wait stepin <Runner 'cat' pid=3782 exit_code=None>
1632866561.276 INFO execute program '/home/runner/.cache/pypoetry/virtualenvs/shellous-dySVFLnW-py3.9/bin/python': <_UnixSubprocessTransport pid=3783 running stdout=<_UnixReadPipeTransport fd=12 polling>>
1632866561.276 INFO Runner._subprocess_spawn stepout <Runner 'echo' pid=3783 exit_code=None> ex=None
1632866561.277 INFO Runner._start stepout <Runner 'echo' pid=3783 exit_code=None> ex=None
1632866561.278 INFO Runner.__aenter__ stepout <Runner 'echo' pid=3783 exit_code=None> ex=None
1632866561.288 INFO copy_bytearray stepin
1632866561.288 INFO write_stream stepin
1632866561.291 DEBUG <SubprocessStreamProtocol stdin=<StreamWriter transport=<_UnixWritePipeTransport fd=13 polling bufsize=3975041>>> pauses writing
1632866561.291 INFO Runner._waiter stepin <Runner 'cat' pid=3782 exit_code=None>
1632866561.292 INFO Runner._waiter stepin <Runner 'echo' pid=3783 exit_code=None>
1632866561.310 INFO <_UnixReadPipeTransport fd=12 polling> was closed by peer
Traceback (most recent call last):
  File "/home/runner/work/shellous/shellous/tests/python_script.py", line 30, in <module>
    _write(data)
  File "/home/runner/work/shellous/shellous/tests/python_script.py", line 16, in _write
    sys.stdout.buffer.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
1632866561.311 DEBUG process 3783 exited with returncode 7
1632866561.311 INFO copy_bytearray stepout ex=None
1632866561.311 INFO Runner.__aexit__ stepin <Runner 'echo' pid=3783 exit_code=None> exc_value=None
1632866561.312 INFO Runner._finish stepin <Runner 'echo' pid=3783 exit_code=None>
1632866561.312 INFO Runner._wait stepin <Runner 'echo' pid=3783 exit_code=None>
1632866561.312 INFO <_UnixSubprocessTransport pid=3783 running stdout=<_UnixReadPipeTransport closed fd=12 closed>> exited with return code 7
1632866561.312 INFO Runner._waiter stepout <Runner 'echo' pid=3783 exit_code=7> ex=None
1632866561.313 INFO Runner._wait stepout <Runner 'echo' pid=3783 exit_code=7> ex=None
1632866561.313 INFO Runner._close stepin <Runner 'echo' pid=3783 exit_code=7>
1632866561.313 INFO Runner._close stepout <Runner 'echo' pid=3783 exit_code=7> ex=None
1632866561.313 INFO Runner._finish stepout <Runner 'echo' pid=3783 exit_code=7> ex=None
1632866561.313 INFO Runner.__aexit__ stepout <Runner 'echo' pid=3783 exit_code=7> ex=None exc_value=None
1632866561.314 INFO harvest_wait cancelled trustee=<Runner 'cat' pid=3782 exit_code=None> cancel_finish=False
1632866561.314 INFO write_stream stepout ex=CancelledError()
1632866561.315 INFO Runner._waiter stepout <Runner 'cat' pid=3782 exit_code=None> ex=CancelledError()
1632866561.315 INFO <_UnixWritePipeTransport fd=13 polling bufsize=3975041> was closed by peer
1632866561.315 INFO Runner.wait cancelled <Runner 'cat' pid=3782 exit_code=None>
1632866561.315 INFO Runner._kill stepin <Runner 'cat' cancelled pid=3782 exit_code=None>
1632866561.316 INFO Runner.signal <Runner 'cat' cancelled pid=3782 exit_code=None> signal=<Signals.SIGTERM: 15>
1632866564.321 INFO harvest_wait timed out trustee=<Runner 'cat' cancelled pid=3782 exit_code=None>
1632866564.321 WARNING Runner.kill <Runner 'cat' cancelled pid=3782 exit_code=None> (ex)=TimeoutError()
1632866564.321 INFO Runner._kill_wait stepin <Runner 'cat' cancelled pid=3782 exit_code=None>
1632866567.327 INFO harvest_wait timed out trustee=<Runner 'cat' cancelled pid=3782 exit_code=None>
1632866567.327 ERROR <Runner 'cat' cancelled pid=3782 exit_code=None> failed to kill process <Process 3782>
1632866567.327 INFO Runner._kill_wait stepout <Runner 'cat' cancelled pid=3782 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.328 INFO Runner._kill stepout <Runner 'cat' cancelled pid=3782 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.328 INFO Runner._wait stepout <Runner 'cat' cancelled pid=3782 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.328 INFO Runner._close stepin <Runner 'cat' cancelled pid=3782 exit_code=None>
1632866567.328 CRITICAL Runner._close process still running <Process 3782>
1632866567.328 INFO Runner._close stepout <Runner 'cat' cancelled pid=3782 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.328 INFO Runner._finish stepout <Runner 'cat' cancelled pid=3782 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.329 INFO Runner.__aexit__ stepout <Runner 'cat' cancelled pid=3782 exit_code=None> ex=RuntimeError('Unable to kill process <Process 3782>') exc_value=None
1632866567.329 INFO PipeRunner._wait stepout <PipeRunner 'cat|echo'> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.329 INFO PipeRunner._finish stepout <PipeRunner 'cat|echo'> ex=RuntimeError('Unable to kill process <Process 3782>')
1632866567.330 INFO PipeRunner.__aexit__ stepout <PipeRunner 'cat|echo'> ex=RuntimeError('Unable to kill process <Process 3782>') exc_value=None
FAILED
------------------------------ live log teardown -------------------------------
1632866567.484 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
```
