### ISSUE TITLE
MacOS: Stuck in test_readme; fails with timeout

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/shellous#87]
```
_________________________________ test_readme __________________________________

kwargs = {}, coro = <coroutine object test_readme at 0x1045bd440>
task = <Task pending name='Task-1249' coro=<test_readme() running at /Users/runner/work/shellous/shellous/tests/test_readme.p...r/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:193>

    @functools.wraps(func)
    def inner(**kwargs):
        coro = func(**kwargs)
        if coro is not None:
            task = asyncio.ensure_future(coro, loop=_loop)
            try:
>               _loop.run_until_complete(task)

../../../Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/lib/python3.9/site-packages/pytest_asyncio/plugin.py:195: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../hostedtoolcache/Python/3.9.7/x64/lib/python3.9/asyncio/base_events.py:629: in run_until_complete
    self.run_forever()
../../../hostedtoolcache/Python/3.9.7/x64/lib/python3.9/asyncio/base_events.py:596: in run_forever
    self._run_once()
../../../hostedtoolcache/Python/3.9.7/x64/lib/python3.9/asyncio/base_events.py:1854: in _run_once
    event_list = self._selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selectors.KqueueSelector object at 0x1046773a0>, timeout = None

    def select(self, timeout=None):
        timeout = None if timeout is None else max(timeout, 0)
        # If max_ev is 0, kqueue will ignore the timeout. For consistent
        # behavior with the other selector classes, we prevent that here
        # (using max). See https://bugs.python.org/issue29255
        max_ev = max(len(self._fd_to_key), 1)
        ready = []
        try:
>           kev_list = self._selector.control(None, max_ev, timeout)
E           Failed: Timeout >10.0s

../../../hostedtoolcache/Python/3.9.7/x64/lib/python3.9/selectors.py:562: Failed
------------------------------ Captured log call -------------------------------
INFO     shellous:log.py:91 Runner.__aenter__ stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None> (macOS-10.15.7 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread SafeChildWatcher)
INFO     shellous:log.py:91 Runner._start stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None>
INFO     shellous:log.py:91 Runner._subprocess_spawn stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None>
INFO     asyncio:base_events.py:1665 execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=7923 running stdin=<_UnixWritePipeTransport fd=10 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=13 polling> stderr=<_UnixReadPipeTransport fd=15 polling>>
INFO     shellous:log.py:102 Runner._subprocess_spawn stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None> ex=None
INFO     shellous:log.py:102 Runner._start stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None> ex=None
INFO     shellous:log.py:102 Runner.__aenter__ stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None> ex=None
INFO     shellous:log.py:135 copy_bytearray stepin
INFO     shellous:log.py:91 Runner._waiter stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None>
```

Complete log:

```
tests/test_readme.py::test_readme 
-------------------------------- live log setup --------------------------------
1632878118.415 DEBUG Using selector: KqueueSelector
1632878118.415 DEBUG Using selector: KqueueSelector
1632878118.416 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
-------------------------------- live log call ---------------------------------
1632878118.419 INFO Runner.__aenter__ stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None> (macOS-10.15.7 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread SafeChildWatcher)
1632878118.419 INFO Runner._start stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None>
1632878118.419 INFO Runner._subprocess_spawn stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None>
1632878118.420 DEBUG execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python' stdin=<pipe> stdout=<pipe> stderr=<pipe>
1632878118.423 DEBUG process '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python' created: pid 7923
1632878118.426 DEBUG Write pipe 10 connected: (<_UnixWritePipeTransport fd=10 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=10 idle bufsize=0>>)
1632878118.427 DEBUG Read pipe 13 connected: (<_UnixReadPipeTransport fd=13 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=13 polling>>)
1632878118.428 DEBUG Read pipe 15 connected: (<_UnixReadPipeTransport fd=15 polling>, <ReadSubprocessPipeProto fd=2 pipe=<_UnixReadPipeTransport fd=15 polling>>)
1632878118.429 INFO execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=7923 running stdin=<_UnixWritePipeTransport fd=10 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=13 polling> stderr=<_UnixReadPipeTransport fd=15 polling>>
1632878118.430 INFO Runner._subprocess_spawn stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None> ex=None
1632878118.431 INFO Runner._start stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None> ex=None
1632878118.431 INFO Runner.__aenter__ stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None> ex=None
1632878118.433 INFO copy_bytearray stepin
1632878118.433 INFO Runner._waiter stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=7923 exit_code=None>
FAILED
------------------------------ live log teardown -------------------------------
1632878128.699 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
```

**Comment by byllyfish** [comment]
Similar issue with uvloop, MacOS, ThreadChildWatcher:

```
tests/test_readme.py::test_readme 
-------------------------------- live log setup --------------------------------
1632878106.545 DEBUG Using selector: KqueueSelector
1632878106.546 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
-------------------------------- live log call ---------------------------------
1632878106.554 INFO Runner.__aenter__ stepin <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=None> (macOS-10.15.7 CPython 3.10.0rc2 uvloop.Loop MainThread ThreadedChildWatcher)
1632878106.555 INFO Runner._start stepin <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=None>
1632878106.555 INFO Runner._subprocess_spawn stepin <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=None>
1632878106.570 INFO Runner._subprocess_spawn stepout <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=10460 exit_code=None> ex=None
1632878106.572 INFO Runner._start stepout <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=10460 exit_code=None> ex=None
1632878106.572 INFO Runner.__aenter__ stepout <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=10460 exit_code=None> ex=None
1632878106.574 INFO copy_bytearray stepin
1632878106.575 INFO Runner._waiter stepin <Runner '...lous-fzoxJzh3-py3.10/bin/python' pid=10460 exit_code=None>
1632878116.626 ERROR Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self created at /Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pytest_asyncio/plugin.py:195>
source_traceback: Object created at (most recent call last):
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pytest_asyncio/plugin.py", line 195, in inner
    _loop.run_until_complete(task)
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pytest_timeout.py", line 200, in handler
    timeout_sigalrm(item, params.timeout)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/pytest_timeout.py", line 375, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.10/lib/python3.10/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >10.0s
Error: The operation was canceled.
```

**Comment by byllyfish** [comment]
See also #72

**Comment by byllyfish** [comment]
After adding more logging, it looks like it is stuck in the final pty-call to ls.

```
tests/test_readme.py::test_readme 
-------------------------------- live log setup --------------------------------
1632880743.298 DEBUG Using selector: KqueueSelector
1632880743.298 DEBUG Using selector: KqueueSelector
1632880743.299 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
-------------------------------- live log call ---------------------------------
1632880743.303 INFO Runner.__aenter__ stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None> (macOS-10.15.7 CPython 3.9.7 asyncio.unix_events._UnixSelectorEventLoop MainThread ThreadedChildWatcher)
1632880743.303 INFO Runner._start stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None>
1632880743.303 INFO Runner._subprocess_spawn stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=None>
1632880743.304 DEBUG execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python' stdin=<pipe> stdout=<pipe> stderr=<pipe>
1632880743.310 DEBUG process '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python' created: pid 5475
1632880743.315 DEBUG Write pipe 10 connected: (<_UnixWritePipeTransport fd=10 idle bufsize=0>, <WriteSubprocessPipeProto fd=0 pipe=<_UnixWritePipeTransport fd=10 idle bufsize=0>>)
1632880743.317 DEBUG Read pipe 11 connected: (<_UnixReadPipeTransport fd=11 polling>, <ReadSubprocessPipeProto fd=1 pipe=<_UnixReadPipeTransport fd=11 polling>>)
1632880743.320 DEBUG Read pipe 15 connected: (<_UnixReadPipeTransport fd=15 polling>, <ReadSubprocessPipeProto fd=2 pipe=<_UnixReadPipeTransport fd=15 polling>>)
1632880743.322 INFO execute program '/Users/runner/Library/Caches/pypoetry/virtualenvs/shellous-fzoxJzh3-py3.9/bin/python': <_UnixSubprocessTransport pid=5475 running stdin=<_UnixWritePipeTransport fd=10 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=11 polling> stderr=<_UnixReadPipeTransport fd=15 polling>>
1632880743.323 INFO Runner._subprocess_spawn stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None> ex=None
1632880743.324 INFO Runner._start stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None> ex=None
1632880743.324 INFO Runner.__aenter__ stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None> ex=None
1632880743.327 INFO copy_bytearray stepin
1632880743.327 INFO Runner._waiter stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None>
1632880743.632 INFO   repl: 'import shellous'
1632880743.636 INFO   repl: 'sh = shellous.context()'
1632880743.640 INFO   repl: 'await sh("echo", "hello, world")'
1632880743.666 INFO   repl: 'echo = sh("echo", "-n")'
1632880743.671 INFO   repl: 'await echo("abc")'
1632880743.684 INFO   repl: 'await echo("abc").set(return_result=True)'
1632880743.717 INFO   repl: 'await sh("cat", "does_not_exist")'
1632880743.756 INFO   repl: 'cmd = "abc" | sh("wc", "-c")'
1632880743.760 INFO   repl: 'await cmd'
1632880743.798 INFO   repl: 'from pathlib import Path'
1632880743.808 INFO   repl: 'cmd = Path("LICENSE") | sh("wc", "-l")'
1632880743.814 INFO   repl: 'await cmd'
1632880743.844 INFO   repl: 'output_file = Path("/tmp/output_file")'
1632880743.850 INFO   repl: 'cmd = sh("echo", "abc") | output_file'
1632880743.855 INFO   repl: 'await cmd'
1632880743.889 INFO   repl: 'output_file.read_bytes()'
1632880743.894 INFO   repl: 'cmd = sh("echo", "def") >> output_file'
1632880743.899 INFO   repl: 'await cmd'
1632880743.932 INFO   repl: 'output_file.read_bytes()'
1632880743.936 INFO   repl: 'cmd = sh("cat", "does_not_exist").stderr(shellous.STDOUT)'
1632880743.939 INFO   repl: 'await cmd.set(exit_codes={0,1})'
1632880743.968 INFO   repl: 'cmd = sh("cat", "does_not_exist").stderr(shellous.INHERIT)'
1632880743.972 INFO   repl: 'await cmd'
1632880743.989 INFO   repl: 'pipe = sh("ls") | sh("grep", "README")'
1632880743.993 INFO   repl: 'await pipe'
1632880744.029 INFO   repl: 'cmd = sh("grep", "README", sh("ls"))'
1632880744.033 INFO   repl: 'await cmd'
1632880744.073 INFO   repl: 'buf = bytearray()'
1632880744.077 INFO   repl: 'cmd = sh("ls") | sh("tee", ~sh("grep", "README") | buf) | shellous.DEVNULL'
1632880744.081 INFO   repl: 'await cmd'
1632880744.122 INFO   repl: 'buf'
1632880744.129 INFO   repl: 'async with pipe.run() as run:\n  data = await run.stdout.readline()\n  print(data)\n'
1632880744.188 INFO   repl: 'async with pipe.run() as run:\n  async for line in run:\n    print(line.rstrip())\n'
1632880744.247 INFO   repl: 'sleep = sh("sleep", 60).set(incomplete_result=True)'
1632880744.251 INFO   repl: 't = asyncio.create_task(sleep.coro())'
1632880744.360 INFO   repl: 't.cancel()'
1632880744.364 INFO   repl: 'await t'
1632880744.370 INFO   repl: 'ls = sh("ls").set(pty=shellous.canonical(cols=20, rows=10, echo=False))'
1632880744.374 INFO   repl: 'await ls("README.md", "CHANGELOG.md")'
1632880746.378 INFO harvest_wait timed out trustee=None
1632880746.378 INFO Runner.__aexit__ stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None> exc_value=TimeoutError()
1632880746.379 INFO Runner._finish stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None>
1632880746.379 INFO Runner._kill stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None>
1632880746.379 INFO Runner.signal <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=None> signal=<Signals.SIGTERM: 15>
1632880746.381 INFO <_UnixReadPipeTransport fd=15 polling> was closed by peer
1632880746.381 DEBUG process 5475 exited with returncode -15
1632880746.382 INFO <_UnixReadPipeTransport fd=11 polling> was closed by peer
1632880746.382 INFO <_UnixWritePipeTransport fd=10 idle bufsize=0> was closed by peer
1632880746.384 INFO <_UnixSubprocessTransport pid=5475 running stdin=<_UnixWritePipeTransport closed fd=10 closed> stdout=<_UnixReadPipeTransport closed fd=11 closed> stderr=<_UnixReadPipeTransport closed fd=15 closed>> exited with return code -15
1632880746.385 INFO Runner._waiter stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=-15> ex=None
1632880746.385 INFO copy_bytearray stepout ex=None
1632880746.386 INFO Runner._kill stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=-15> ex=TimeoutError()
1632880746.386 INFO Runner._close stepin <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=-15>
1632880746.388 INFO Runner._close stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=-15> ex=TimeoutError()
1632880746.388 INFO Runner._finish stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=-15> ex=TimeoutError()
1632880746.388 INFO Runner.__aexit__ stepout <Runner '...llous-fzoxJzh3-py3.9/bin/python' pid=5475 exit_code=-15> ex=TimeoutError() exc_value=TimeoutError()
FAILED
------------------------------ live log teardown -------------------------------
1632880746.505 DEBUG Close <_UnixSelectorEventLoop running=False closed=False debug=True>
```

**Comment by byllyfish** [comment]
Old report. Closing.
